import nltk
from nltk.stem.lancaster import LancasterStemmer
stemmer = LancasterStemmer() 
import numpy as np
import time
import datetime
import json


training_data = []
training_data.append({"class":"0:Go To TV", "sentence":"switch to tv"})
training_data.append({"class":"0:Go To TV", "sentence":"switch to television"})
training_data.append({"class":"0:Go To TV", "sentence":"go to television"})
training_data.append({"class":"0:Go To TV", "sentence":"play television"})
training_data.append({"class":"0:Go To TV", "sentence":"television"})
training_data.append({"class":"0:Go To TV", "sentence":"tv"})
training_data.append({"class":"0:Go To TV", "sentence":"play tv"})
training_data.append({"class":"0:Go To TV", "sentence":"go to tv"})
training_data.append({"class":"0:Go To TV", "sentence":"start tv"})
training_data.append({"class":"0:Go To TV", "sentence":"jump to tv"})
training_data.append({"class":"0:Go To TV", "sentence":"turn on tv"})
training_data.append({"class":"0:Go To TV", "sentence":"move to tv"})
training_data.append({"class":"0:Go To TV", "sentence":"turn on tv"})
training_data.append({"class":"0:Go To TV", "sentence":"program"})
training_data.append({"class":"0:Go To TV", "sentence":"go to program"})
training_data.append({"class":"0:Go To TV", "sentence":"switch to program"})
training_data.append({"class":"0:Go To TV", "sentence":"move to program"})
training_data.append({"class":"0:Go To TV", "sentence":"jump to program"})
training_data.append({"class":"0:Go To TV", "sentence":"start program"})
training_data.append({"class":"0:Go To TV", "sentence":"open program"})
training_data.append({"class":"0:Go To TV", "sentence":"tv shows"})
training_data.append({"class":"0:Go To TV", "sentence":"move out of education video"})
training_data.append({"class":"0:Go To TV", "sentence":"back to tv show video"})
training_data.append({"class":"0:Go To TV", "sentence":"back to tv"})

training_data.append({"class":"1:Academics", "sentence":"adademic"})
training_data.append({"class":"1:Academics", "sentence":"academy"})
training_data.append({"class":"1:Academics", "sentence":"open academic"})
training_data.append({"class":"1:Academics", "sentence":"go to academic"})
training_data.append({"class":"1:Academics", "sentence":"move to academic"})
training_data.append({"class":"1:Academics", "sentence":"jump to academic"})
training_data.append({"class":"1:Academics", "sentence":"turn on academic"})
training_data.append({"class":"1:Academics", "sentence":"start to academic"})
training_data.append({"class":"1:Academics", "sentence":"execute academic"})
training_data.append({"class":"1:Academics", "sentence":"adademic video"})
training_data.append({"class":"1:Academics", "sentence":"academy video"})
training_data.append({"class":"1:Academics", "sentence":"open academic video"})
training_data.append({"class":"1:Academics", "sentence":"go to academic video"})
training_data.append({"class":"1:Academics", "sentence":"move to academic video"})
training_data.append({"class":"1:Academics", "sentence":"jump to academic video"})
training_data.append({"class":"1:Academics", "sentence":"turn on academic video"})
training_data.append({"class":"1:Academics", "sentence":"start to academic video"})
training_data.append({"class":"1:Academics", "sentence":"execute academic video"})

training_data.append({"class":"2:GK", "sentence":"gk"})
training_data.append({"class":"2:GK", "sentence":"general knowledge"})
training_data.append({"class":"2:GK", "sentence":"open gk"})
training_data.append({"class":"2:GK", "sentence":"go to GK"})
training_data.append({"class":"2:GK", "sentence":"move to GK"})
training_data.append({"class":"2:GK", "sentence":"jump to gk"})
training_data.append({"class":"2:GK", "sentence":"turn on gk"})
training_data.append({"class":"2:GK", "sentence":"start gk"})
training_data.append({"class":"2:GK", "sentence":"execute gk"})
training_data.append({"class":"2:GK", "sentence":"start general knowledge"})
training_data.append({"class":"2:GK", "sentence":"open general knowledge"})
training_data.append({"class":"2:GK", "sentence":"go to general knowledge"})
training_data.append({"class":"2:GK", "sentence":"jump to general knowledge"})
training_data.append({"class":"2:GK", "sentence":"move to general knowledge"})
training_data.append({"class":"2:GK", "sentence":"execute general knowledge"})
training_data.append({"class":"2:GK", "sentence":"gk video"})
training_data.append({"class":"2:GK", "sentence":"general knowledge video"})
training_data.append({"class":"2:GK", "sentence":"open gk video"})
training_data.append({"class":"2:GK", "sentence":"go to GK video"})
training_data.append({"class":"2:GK", "sentence":"move to GK video"})
training_data.append({"class":"2:GK", "sentence":"jump to gk video"})
training_data.append({"class":"2:GK", "sentence":"turn on gk video"})
training_data.append({"class":"2:GK", "sentence":"start gk video"})
training_data.append({"class":"2:GK", "sentence":"execute gk"})
training_data.append({"class":"2:GK", "sentence":"start general knowledge video"})
training_data.append({"class":"2:GK", "sentence":"open general knowledge video"})
training_data.append({"class":"2:GK", "sentence":"go to general knowledge video"})
training_data.append({"class":"2:GK", "sentence":"jump to general knowledge video"})
training_data.append({"class":"2:GK", "sentence":"move to general knowledge video"})
training_data.append({"class":"2:GK", "sentence":"execute general knowledge video"})

training_data.append({"class":"3:Revision", "sentence":"revision"})
training_data.append({"class":"3:Revision", "sentence":"revise"})
training_data.append({"class":"3:Revision", "sentence":"i want to revise"})
training_data.append({"class":"3:Revision", "sentence":"open revision"})
training_data.append({"class":"3:Revision", "sentence":"begin revision"})
training_data.append({"class":"3:Revision", "sentence":"start revision"})
training_data.append({"class":"3:Revision", "sentence":"go to revision"})
training_data.append({"class":"3:Revision", "sentence":"jump to revision"})
training_data.append({"class":"3:Revision", "sentence":"turn on revision"})
training_data.append({"class":"3:Revision", "sentence":"execute revision"})
training_data.append({"class":"3:Revision", "sentence":"revision video"})
training_data.append({"class":"3:Revision", "sentence":"open revision video"})
training_data.append({"class":"3:Revision", "sentence":"start revision video"})
training_data.append({"class":"3:Revision", "sentence":"begin revision video"})
training_data.append({"class":"3:Revision", "sentence":"go to revision video"})
training_data.append({"class":"3:Revision", "sentence":"move to revision video"})
training_data.append({"class":"3:Revision", "sentence":"jump to revision application"})
training_data.append({"class":"3:Revision", "sentence":"revision app"})
training_data.append({"class":"3:Revision", "sentence":"go to revision application"})
training_data.append({"class":"3:Revision", "sentence":"begin to revision application"})
training_data.append({"class":"3:Revision", "sentence":"start revision application"})
training_data.append({"class":"3:Revision", "sentence":"open revision application"})
training_data.append({"class":"3:Revision", "sentence":"summary video"})

training_data.append({"class":"4:Progress", "sentence":"progress application"})
training_data.append({"class":"4:Progress", "sentence":"start progress application"})
training_data.append({"class":"4:Progress", "sentence":"go to progress application"})
training_data.append({"class":"4:Progress", "sentence":"report"})
training_data.append({"class":"4:Progress", "sentence":"show me report"})
training_data.append({"class":"4:Progress", "sentence":"jump to progress application"})
training_data.append({"class":"4:Progress", "sentence":"execute progress application"})
training_data.append({"class":"4:Progress", "sentence":"progress application"})
training_data.append({"class":"4:Progress", "sentence":"start progress"})
training_data.append({"class":"4:Progress", "sentence":"go to progress"})
training_data.append({"class":"4:Progress", "sentence":"turn on progress"})
training_data.append({"class":"4:Progress", "sentence":"jump to progress"})
training_data.append({"class":"4:Progress", "sentence":"move to progress"})
training_data.append({"class":"4:Progress", "sentence":"execute progress"})
training_data.append({"class":"4:Progress", "sentence":"show my progress"})
training_data.append({"class":"4:Progress", "sentence":"display progress"})
training_data.append({"class":"4:Progress", "sentence":"view progress"})
training_data.append({"class":"4:Progress", "sentence":"give progress"})
training_data.append({"class":"4:Progress", "sentence":"progress report"})
training_data.append({"class":"4:Progress", "sentence":"give progress report"})
training_data.append({"class":"4:Progress", "sentence":"my progress report"})
training_data.append({"class":"4:Progress", "sentence":"my progress"})
training_data.append({"class":"4:Progress", "sentence":"open my progress"})
training_data.append({"class":"4:Progress", "sentence":"go to my progress"})
training_data.append({"class":"4:Progress", "sentence":"switch to my progress"})
training_data.append({"class":"4:Progress", "sentence":"switch my progress"})
training_data.append({"class":"4:Progress", "sentence":"jump to my progress"})
training_data.append({"class":"4:Progress", "sentence":"move to my progress"})
training_data.append({"class":"4:Progress", "sentence":"where i am"})
training_data.append({"class":"4:Progress", "sentence":"education report"})
training_data.append({"class":"4:Progress", "sentence":"educational report"})
training_data.append({"class":"4:Progress", "sentence":"statistic"})
training_data.append({"class":"4:Progress", "sentence":"video statistic"})
training_data.append({"class":"4:Progress", "sentence":"statistics"})
training_data.append({"class":"4:Progress", "sentence":"video statistics"})
training_data.append({"class":"4:Progress", "sentence":"stats"})
training_data.append({"class":"4:Progress", "sentence":"video stats"})

training_data.append({"class":"5:TIPS", "sentence":"tips"})
training_data.append({"class":"5:TIPS", "sentence":"open tips"})
training_data.append({"class":"5:TIPS", "sentence":"switch to tips"})
training_data.append({"class":"5:TIPS", "sentence":"go to tips"})
training_data.append({"class":"5:TIPS", "sentence":"turn on tips"})
training_data.append({"class":"5:TIPS", "sentence":"start tips"})
training_data.append({"class":"5:TIPS", "sentence":"give me some tips"})
training_data.append({"class":"5:TIPS", "sentence":"tip"})
training_data.append({"class":"5:TIPS", "sentence":"open tip"})
training_data.append({"class":"5:TIPS", "sentence":"switch to tips application"})
training_data.append({"class":"5:TIPS", "sentence":"go to tips application"})
training_data.append({"class":"5:TIPS", "sentence":"jump to tips application"})
training_data.append({"class":"5:TIPS", "sentence":"move to tips application"})
training_data.append({"class":"5:TIPS", "sentence":"turn on tips application"})
training_data.append({"class":"5:TIPS", "sentence":"start tips application"})

training_data.append({"class":"6:Test", "sentence":"start test"})
training_data.append({"class":"6:Test", "sentence":"switch test"})
training_data.append({"class":"6:Test", "sentence":"open test"})
training_data.append({"class":"6:Test", "sentence":"go to test"})
training_data.append({"class":"6:Test", "sentence":"jump to test"})
training_data.append({"class":"6:Test", "sentence":"execute test"})
training_data.append({"class":"6:Test", "sentence":"turn on test"})
training_data.append({"class":"6:Test", "sentence":"start test application"})
training_data.append({"class":"6:Test", "sentence":"open test application"})
training_data.append({"class":"6:Test", "sentence":"go to test application"})
training_data.append({"class":"6:Test", "sentence":"want to give test"})
training_data.append({"class":"6:Test", "sentence":"jump to test application"})
training_data.append({"class":"6:Test", "sentence":"move to test application"})
training_data.append({"class":"6:Test", "sentence":"execute test application"})
training_data.append({"class":"6:Test", "sentence":"turn on test application"})
training_data.append({"class":"6:Test", "sentence":"edutest"})
training_data.append({"class":"6:Test", "sentence":"edu test"})
training_data.append({"class":"6:Test", "sentence":"start exam"})
training_data.append({"class":"6:Test", "sentence":"switch exam"})
training_data.append({"class":"6:Test", "sentence":"open exam"})
training_data.append({"class":"6:Test", "sentence":"go to exam"})
training_data.append({"class":"6:Test", "sentence":"jump to exam"})
training_data.append({"class":"6:Test", "sentence":"turn on exam"})
training_data.append({"class":"6:Test", "sentence":"execute exam"})
training_data.append({"class":"6:Test", "sentence":"start examination"})
training_data.append({"class":"6:Test", "sentence":"switch examination"})
training_data.append({"class":"6:Test", "sentence":"open examination"})
training_data.append({"class":"6:Test", "sentence":"go to examination"})
training_data.append({"class":"6:Test", "sentence":"jump to examination"})
training_data.append({"class":"6:Test", "sentence":"turn on examination"})
training_data.append({"class":"6:Test", "sentence":"execute examination"})

training_data.append({"class":"7:Library", "sentence":"library"})
training_data.append({"class":"7:Library", "sentence":"book"})
training_data.append({"class":"7:Library", "sentence":"script"})
training_data.append({"class":"7:Library", "sentence":"start library"})
training_data.append({"class":"7:Library", "sentence":"open library"})
training_data.append({"class":"7:Library", "sentence":"go to library"})
training_data.append({"class":"7:Library", "sentence":"jump to library"})
training_data.append({"class":"7:Library", "sentence":"move to library"})
training_data.append({"class":"7:Library", "sentence":"execute library"})
training_data.append({"class":"7:Library", "sentence":"edulibrary"})
training_data.append({"class":"7:Library", "sentence":"edu library"})
training_data.append({"class":"7:Library", "sentence":"library application"})
training_data.append({"class":"7:Library", "sentence":"start library application"})
training_data.append({"class":"7:Library", "sentence":"open library application"})
training_data.append({"class":"7:Library", "sentence":"go to library application"})
training_data.append({"class":"7:Library", "sentence":"turn on library application"})
training_data.append({"class":"7:Library", "sentence":"jump to library application"})
training_data.append({"class":"7:Library", "sentence":"move to library application"})
training_data.append({"class":"7:Library", "sentence":"execute library application"})

training_data.append({"class":"8:Edueye", "sentence":"edueye"})
training_data.append({"class":"8:Edueye", "sentence":"edu eye"})
training_data.append({"class":"8:Edueye", "sentence":"open edu eye"})
training_data.append({"class":"8:Edueye", "sentence":"start edu eye"})
training_data.append({"class":"8:Edueye", "sentence":"turn on edu eye"})
training_data.append({"class":"8:Edueye", "sentence":"jump to edu eye"})
training_data.append({"class":"8:Edueye", "sentence":"switch to edu eye"})
training_data.append({"class":"8:Edueye", "sentence":"go to edu eye"})
training_data.append({"class":"8:Edueye", "sentence":"move to edu eye"})
training_data.append({"class":"8:Edueye", "sentence":"move to parental control"})
training_data.append({"class":"8:Edueye", "sentence":"go to parental control"})
training_data.append({"class":"8:Edueye", "sentence":"jump to parental control"})
training_data.append({"class":"8:Edueye", "sentence":"start parental control"})
training_data.append({"class":"8:Edueye", "sentence":"open parental control"})
training_data.append({"class":"8:Edueye", "sentence":"execute parental control"})
training_data.append({"class":"8:Edueye", "sentence":"control on channel"})
training_data.append({"class":"8:Edueye", "sentence":"control channel"})
training_data.append({"class":"8:Edueye", "sentence":"channel control"})

training_data.append({"class":"9:Update app", "sentence":"update application"})
training_data.append({"class":"9:Update app", "sentence":"open update application"})
training_data.append({"class":"9:Update app", "sentence":"start update application"})
training_data.append({"class":"9:Update app", "sentence":"go to update application"})
training_data.append({"class":"9:Update app", "sentence":"turn on update application"})
training_data.append({"class":"9:Update app", "sentence":"jump to update application"})
training_data.append({"class":"9:Update app", "sentence":"switch to update application"})
training_data.append({"class":"9:Update app", "sentence":"execute update application"})
training_data.append({"class":"9:Update app", "sentence":"go to update app"})
training_data.append({"class":"9:Update app", "sentence":"start update app"})
training_data.append({"class":"9:Update app", "sentence":"turn on update app"})
training_data.append({"class":"9:Update app", "sentence":"jump to update app"})
training_data.append({"class":"9:Update app", "sentence":"switch to update app"})
training_data.append({"class":"9:Update app", "sentence":"execute update app"})
training_data.append({"class":"9:Update app", "sentence":"update app"})
training_data.append({"class":"9:Update app", "sentence":"edu update app"})
training_data.append({"class":"9:Update app", "sentence":"edu update application"})
training_data.append({"class":"9:Update app", "sentence":"eduupdate app"})
training_data.append({"class":"9:Update app", "sentence":"eduupdate application"})
training_data.append({"class":"9:Update app", "sentence":"package updater"})
training_data.append({"class":"9:Update app", "sentence":"update video"})
training_data.append({"class":"9:Update app", "sentence":"update my video"})
training_data.append({"class":"9:Update app", "sentence":"download video"})
training_data.append({"class":"9:Update app", "sentence":"update my video package"})
training_data.append({"class":"9:Update app", "sentence":"update video package"})

training_data.append({"class":"10:Edu cast", "sentence":"edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"miracast"})
training_data.append({"class":"10:Edu cast", "sentence":"screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"open edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"open mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"open screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"open screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"open screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"start edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"start mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"start screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"start screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"start screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"go to edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"go to mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"go to screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"go to screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"go to screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"jump to edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"jump to mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"jump to screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"jump to screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"jump to screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"open edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"open mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"open screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"open screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"open screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"execute edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"execute mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"execute screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"execute screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"execute screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"move to edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"move to mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"move to screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"move to screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"move to screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"turn on edu cast"})
training_data.append({"class":"10:Edu cast", "sentence":"turn on mira cast"})
training_data.append({"class":"10:Edu cast", "sentence":"turn on screen cast"})
training_data.append({"class":"10:Edu cast", "sentence":"turn on screenmirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"turn on screen mirroring"})
training_data.append({"class":"10:Edu cast", "sentence":"mobile screen"})
training_data.append({"class":"10:Edu cast", "sentence":"open mobile screen"})
training_data.append({"class":"10:Edu cast", "sentence":"start mobile screen"})
training_data.append({"class":"10:Edu cast", "sentence":"show mobile screen"})
training_data.append({"class":"10:Edu cast", "sentence":"mirror mobile screen"})
training_data.append({"class":"10:Edu cast", "sentence":"mirror tab screen"})
training_data.append({"class":"10:Edu cast", "sentence":"mirror ipad screen"})
training_data.append({"class":"10:Edu cast", "sentence":"mirror tv screen"})
training_data.append({"class":"10:Edu cast", "sentence":"cast tv screen"})
training_data.append({"class":"10:Edu cast", "sentence":"cast mobile screen"})
training_data.append({"class":"10:Edu cast", "sentence":"cast tab screen"})
training_data.append({"class":"10:Edu cast", "sentence":"cast ipad screen"})

training_data.append({"class":"11:Browser", "sentence":"browser"})
training_data.append({"class":"11:Browser", "sentence":"website"})
training_data.append({"class":"11:Browser", "sentence":"website application"})
training_data.append({"class":"11:Browser", "sentence":"web application"})
training_data.append({"class":"11:Browser", "sentence":"start browser"})
training_data.append({"class":"11:Browser", "sentence":"open browser"})
training_data.append({"class":"11:Browser", "sentence":"turn on browser"})
training_data.append({"class":"11:Browser", "sentence":"go to browser"})
training_data.append({"class":"11:Browser", "sentence":"move to browser"})
training_data.append({"class":"11:Browser", "sentence":"jump to browser"})
training_data.append({"class":"11:Browser", "sentence":"switch to browser"})
training_data.append({"class":"11:Browser", "sentence":"execute browser"})
training_data.append({"class":"11:Browser", "sentence":"edubrowser"})
training_data.append({"class":"11:Browser", "sentence":"edu browser"})

training_data.append({"class":"12:FAQ", "sentence":"faq"})
training_data.append({"class":"12:FAQ", "sentence":"open faq"})
training_data.append({"class":"12:FAQ", "sentence":"start faq"})
training_data.append({"class":"12:FAQ", "sentence":"execute faq"})
training_data.append({"class":"12:FAQ", "sentence":"go to faq"})
training_data.append({"class":"12:FAQ", "sentence":"jump to faq"})
training_data.append({"class":"12:FAQ", "sentence":"switch to faq"})
training_data.append({"class":"12:FAQ", "sentence":"move to faq"})
training_data.append({"class":"12:FAQ", "sentence":"frequently asked question"})
training_data.append({"class":"12:FAQ", "sentence":"frequently asked questions"})

training_data.append({"class":"13:WI-FI Setting", "sentence":"wi-fi"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wi-fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"open wi-fi seting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"go to wi-fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"jump to wi-fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"switch to wi-fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"move to wi-fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wifi"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wifi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"open wifi seting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"go to wifi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"jump to wifi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"switch to wifi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"move to wifi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wi fi"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wi fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"open wi fi seting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"go to wi fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"jump to wi fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"switch to wi fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"move to wi fi setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wi-fi and hotspot"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wi-fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"open wi-fi and hotspot seting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"go to wi-fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"jump to wi-fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"switch to wi-fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"move to wi-fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wifi and hotspot"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wifi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"open wifi and hotspot seting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"go to wifi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"jump to wifi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"switch to wifi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"move to wifi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wifi and hotspot"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"wi fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"open wi fi and hotspot seting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"go to wi fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"jump to wi fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"switch to wi fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"move to wi fi and hotspot setting"})
training_data.append({"class":"13:WI-FI Setting", "sentence":"hotspot setting"})

training_data.append({"class":"14:Ethernet", "sentence":"ethernet"})
training_data.append({"class":"14:Ethernet", "sentence":"ethernet connection"})
training_data.append({"class":"14:Ethernet", "sentence":"open ethernet"})
training_data.append({"class":"14:Ethernet", "sentence":"start ethernet"})
training_data.append({"class":"14:Ethernet", "sentence":"go to ethernet"})
training_data.append({"class":"14:Ethernet", "sentence":"jump to ethernet"})
training_data.append({"class":"14:Ethernet", "sentence":"move to ethernet"})
training_data.append({"class":"14:Ethernet", "sentence":"switch to ethernet"})
training_data.append({"class":"14:Ethernet", "sentence":"lan"})
training_data.append({"class":"14:Ethernet", "sentence":"dhcp"})
training_data.append({"class":"14:Ethernet", "sentence":"pppoe"})

training_data.append({"class":"15:UserProfile", "sentence":"user profile"})
training_data.append({"class":"15:UserProfile", "sentence":"user profile"})
training_data.append({"class":"15:UserProfile", "sentence":"user profile setting"})
training_data.append({"class":"15:UserProfile", "sentence":"open user profile"})
training_data.append({"class":"15:UserProfile", "sentence":"start user profile"})
training_data.append({"class":"15:UserProfile", "sentence":"my profile"})
training_data.append({"class":"15:UserProfile", "sentence":"open my profile"})
training_data.append({"class":"15:UserProfile", "sentence":"display my profile"})
training_data.append({"class":"15:UserProfile", "sentence":"go to profile"})
training_data.append({"class":"15:UserProfile", "sentence":"user setting"})
training_data.append({"class":"15:UserProfile", "sentence":"profile setting"})

training_data.append({"class":"16:DisplaySetting", "sentence":"display setting"})
training_data.append({"class":"16:DisplaySetting", "sentence":"display"})
training_data.append({"class":"16:DisplaySetting", "sentence":"start display setting"})
training_data.append({"class":"16:DisplaySetting", "sentence":"open display setting"})
training_data.append({"class":"16:DisplaySetting", "sentence":"go to display setting"})
training_data.append({"class":"16:DisplaySetting", "sentence":"switch to display setting"})
training_data.append({"class":"16:DisplaySetting", "sentence":"jump to display setting"})
training_data.append({"class":"16:DisplaySetting", "sentence":"move to display setting"})
training_data.append({"class":"16:DisplaySetting", "sentence":"execute display setting"})
training_data.append({"class":"16:DisplaySetting", "sentence":"display resolution"})


training_data.append({"class":"17:DatenTime", "sentence":"date and time"})
training_data.append({"class":"17:DatenTime", "sentence":"open date and time"})
training_data.append({"class":"17:DatenTime", "sentence":"go to date and time"})
training_data.append({"class":"17:DatenTime", "sentence":"jump to date and time"})
training_data.append({"class":"17:DatenTime", "sentence":"switch to date and time"})
training_data.append({"class":"17:DatenTime", "sentence":"execute date and time"})
training_data.append({"class":"17:DatenTime", "sentence":"show date and time"})
training_data.append({"class":"17:DatenTime", "sentence":"date"})
training_data.append({"class":"17:DatenTime", "sentence":"show date"})
training_data.append({"class":"17:DatenTime", "sentence":"time"})
training_data.append({"class":"17:DatenTime", "sentence":"show time"})

training_data.append({"class":"18:USB", "sentence":"usb"})
training_data.append({"class":"18:USB", "sentence":"open usb"})
training_data.append({"class":"18:USB", "sentence":"go to usb"})
training_data.append({"class":"18:USB", "sentence":"go to usb setting"})
training_data.append({"class":"18:USB", "sentence":"pendrive"})
training_data.append({"class":"18:USB", "sentence":"open pendrive"})
training_data.append({"class":"18:USB", "sentence":"go to pendrive"})
training_data.append({"class":"18:USB", "sentence":"go to pendrive setting"})


training_data.append({"class":"19:LearningList", "sentence":"learning list"})
training_data.append({"class":"19:LearningList", "sentence":"video list"})
training_data.append({"class":"19:LearningList", "sentence":"schedule video"})
training_data.append({"class":"19:LearningList", "sentence":"schedule learning video"})
training_data.append({"class":"19:LearningList", "sentence":"open learning list"})
training_data.append({"class":"19:LearningList", "sentence":"start learning list"})
training_data.append({"class":"19:LearningList", "sentence":"begin learning list"})
training_data.append({"class":"19:LearningList", "sentence":"go to learning list"})
training_data.append({"class":"19:LearningList", "sentence":"jump to learning list"})
training_data.append({"class":"19:LearningList", "sentence":"switch to learning list"})
training_data.append({"class":"19:LearningList", "sentence":"open play list"})
training_data.append({"class":"19:LearningList", "sentence":"play list"})
training_data.append({"class":"19:LearningList", "sentence":"start play list"})
training_data.append({"class":"19:LearningList", "sentence":"begin play list"})
training_data.append({"class":"19:LearningList", "sentence":"go to play list"})
training_data.append({"class":"19:LearningList", "sentence":"jump to play list"})
training_data.append({"class":"19:LearningList", "sentence":"switch to play list"})
training_data.append({"class":"19:LearningList", "sentence":"open playlist"})
training_data.append({"class":"19:LearningList", "sentence":"playlist"})
training_data.append({"class":"19:LearningList", "sentence":"start playlist"})
training_data.append({"class":"19:LearningList", "sentence":"begin playlist"})
training_data.append({"class":"19:LearningList", "sentence":"go to playlist"})
training_data.append({"class":"19:LearningList", "sentence":"jump to playlist"})
training_data.append({"class":"19:LearningList", "sentence":"switch to playlist"})

training_data.append({"class":"20:Reset", "sentence":"reset"})
training_data.append({"class":"20:Reset", "sentence":"factory reset"})
training_data.append({"class":"20:Reset", "sentence":"format"})
training_data.append({"class":"20:Reset", "sentence":"format device"})


training_data.append({"class":"21:Update", "sentence":"update setting"})
training_data.append({"class":"21:Update", "sentence":"software update"})

training_data.append({"class":"22:About", "sentence":"about"})
training_data.append({"class":"22:About", "sentence":"what is edu tree"})
training_data.append({"class":"22:About", "sentence":"what is edutree"})
training_data.append({"class":"22:About", "sentence":"device information"})
training_data.append({"class":"22:About", "sentence":"open about"})
training_data.append({"class":"22:About", "sentence":"go to about"})
training_data.append({"class":"22:About", "sentence":"switch to about"})
training_data.append({"class":"22:About", "sentence":"jump to about"})


training_data.append({"class":"23:Snake n ladder", "sentence":"snakes and ladder"})
training_data.append({"class":"23:Snake n ladder", "sentence":"snake"})
training_data.append({"class":"23:Snake n ladder", "sentence":"snake game"})
training_data.append({"class":"23:Snake n ladder", "sentence":"game"})
training_data.append({"class":"23:Snake n ladder", "sentence":"games"})
training_data.append({"class":"23:Snake n ladder", "sentence":"play"})
training_data.append({"class":"23:Snake n ladder", "sentence":"play snake game"})
training_data.append({"class":"23:Snake n ladder", "sentence":"play games"})
training_data.append({"class":"23:Snake n ladder", "sentence":"play game"})

training_data.append({"class":"24:Close", "sentence":"close"})
training_data.append({"class":"24:Close", "sentence":"close Academics"})
training_data.append({"class":"24:Close", "sentence":"close gk"})
training_data.append({"class":"24:Close", "sentence":"close general knowledge"})
training_data.append({"class":"24:Close", "sentence":"close revision"})
training_data.append({"class":"24:Close", "sentence":"close revision application"})
training_data.append({"class":"24:Close", "sentence":"close progress"})
training_data.append({"class":"24:Close", "sentence":"close progress application"})
training_data.append({"class":"24:Close", "sentence":"close my progress"})
training_data.append({"class":"24:Close", "sentence":"close my progress application"})
training_data.append({"class":"24:Close", "sentence":"close tips"})
training_data.append({"class":"24:Close", "sentence":"close tips application"})
training_data.append({"class":"24:Close", "sentence":"close test"})
training_data.append({"class":"24:Close", "sentence":"close test application"})
training_data.append({"class":"24:Close", "sentence":"close exam"})
training_data.append({"class":"24:Close", "sentence":"close exam application"})
training_data.append({"class":"24:Close", "sentence":"close exam application"})
training_data.append({"class":"24:Close", "sentence":"close library"})
training_data.append({"class":"24:Close", "sentence":"close parental control"})
training_data.append({"class":"24:Close", "sentence":"close edueye"})
training_data.append({"class":"24:Close", "sentence":"close edu eye"})
training_data.append({"class":"24:Close", "sentence":"close update"})
training_data.append({"class":"24:Close", "sentence":"close edu update"})
training_data.append({"class":"24:Close", "sentence":"close update application"})
training_data.append({"class":"24:Close", "sentence":"close cast"})
training_data.append({"class":"24:Close", "sentence":"close miracast"})
training_data.append({"class":"24:Close", "sentence":"close mira cast"})
training_data.append({"class":"24:Close", "sentence":"close screenmirroring"})
training_data.append({"class":"24:Close", "sentence":"close screen mirroring"})
training_data.append({"class":"24:Close", "sentence":"close screen cast"})
training_data.append({"class":"24:Close", "sentence":"close edu cast"})
training_data.append({"class":"24:Close", "sentence":"close educast"})
training_data.append({"class":"24:Close", "sentence":"close browser"})
training_data.append({"class":"24:Close", "sentence":"close faq"})
training_data.append({"class":"24:Close", "sentence":"close frequently asked question"})
training_data.append({"class":"24:Close", "sentence":"close wi-fi settings"})
training_data.append({"class":"24:Close", "sentence":"close wifi settings"})
training_data.append({"class":"24:Close", "sentence":"close wi fi settings"})
training_data.append({"class":"24:Close", "sentence":"close wi fi and hotspot settings"})
training_data.append({"class":"24:Close", "sentence":"close hotspot settings"})
training_data.append({"class":"24:Close", "sentence":"close user profile"})
training_data.append({"class":"24:Close", "sentence":"close user profile settings"})
training_data.append({"class":"24:Close", "sentence":"close profile settings"})
training_data.append({"class":"24:Close", "sentence":"close profile settings"})
training_data.append({"class":"24:Close", "sentence":"close settings"})
training_data.append({"class":"24:Close", "sentence":"close date and time"})
training_data.append({"class":"24:Close", "sentence":"close learning list"})
training_data.append({"class":"24:Close", "sentence":"close play list"})
training_data.append({"class":"24:Close", "sentence":"close about"})
training_data.append({"class":"24:Close", "sentence":"close game"})
training_data.append({"class":"24:Close", "sentence":"close snake game"})
training_data.append({"class":"24:Close", "sentence":"close puzzle game"})
training_data.append({"class":"24:Close", "sentence":"close video"})
training_data.append({"class":"24:Close", "sentence":"close trending page"})
training_data.append({"class":"24:Close", "sentence":"close trends page"})
training_data.append({"class":"24:Close", "sentence":"close hotstar"})
training_data.append({"class":"24:Close", "sentence":"close mxplayer"})
training_data.append({"class":"24:Close", "sentence":"close mx player"})
training_data.append({"class":"24:Close", "sentence":"close it"})
training_data.append({"class":"24:Close", "sentence":"close application"})
training_data.append({"class":"24:Close", "sentence":"end"})
training_data.append({"class":"24:Close", "sentence":"stop"})
training_data.append({"class":"24:Close", "sentence":"exit"})
training_data.append({"class":"24:Close", "sentence":"turn off"})
training_data.append({"class":"24:Close", "sentence":"turn of"})


training_data.append({"class":"25:PlayVideo", "sentence":"play"})
training_data.append({"class":"25:PlayVideo", "sentence":"play video"})
training_data.append({"class":"25:PlayVideo", "sentence":"start video"})
training_data.append({"class":"25:PlayVideo", "sentence":"execute video"})
training_data.append({"class":"25:PlayVideo", "sentence":"begin video"})
training_data.append({"class":"25:PlayVideo", "sentence":"resume video"})
training_data.append({"class":"25:PlayVideo", "sentence":"run video"})
training_data.append({"class":"25:PlayVideo", "sentence":"continue video"})


training_data.append({"class":"26:PauseVideo", "sentence":"pause"})
training_data.append({"class":"26:PauseVideo", "sentence":"pause video"})
training_data.append({"class":"26:PauseVideo", "sentence":"hold video"})
training_data.append({"class":"26:PauseVideo", "sentence":"hold on"})

training_data.append({"class":"27:StopVideo", "sentence":"stop"})
training_data.append({"class":"27:StopVideo", "sentence":"stop video"})
training_data.append({"class":"27:StopVideo", "sentence":"stop the video"})
training_data.append({"class":"27:StopVideo", "sentence":"end video"})
training_data.append({"class":"27:StopVideo", "sentence":"end the video"})

training_data.append({"class":"28:NextVideo", "sentence":"next video"})
training_data.append({"class":"28:NextVideo", "sentence":"upcoming video"})
training_data.append({"class":"28:NextVideo", "sentence":"move to next video"})
training_data.append({"class":"28:NextVideo", "sentence":"open next video"})
training_data.append({"class":"28:NextVideo", "sentence":"go to next video"})
training_data.append({"class":"28:NextVideo", "sentence":"start next video"})
training_data.append({"class":"28:NextVideo", "sentence":"jump to next video"})
training_data.append({"class":"28:NextVideo", "sentence":"move to next video"})
training_data.append({"class":"28:NextVideo", "sentence":"switch to next video"})
training_data.append({"class":"28:NextVideo", "sentence":"execute next video"})
training_data.append({"class":"28:NextVideo", "sentence":"begin next video"})
training_data.append({"class":"28:NextVideo", "sentence":"run next video"})

training_data.append({"class":"29:PreviousVideo", "sentence":"previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"previous"})
training_data.append({"class":"29:PreviousVideo", "sentence":"go to previous"})
training_data.append({"class":"29:PreviousVideo", "sentence":"move to previous"})
training_data.append({"class":"29:PreviousVideo", "sentence":"last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"open previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"open last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"open recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"run previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"run last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"run recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"start previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"start last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"start recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"go to previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"go to last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"go to recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"jump to previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"jump to last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"jump to recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"move to previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"move to last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"move to recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"switch to previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"switch to last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"switch to recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"begin to previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"begin to last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"begin to recent video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"execute to previous video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"execute to last video"})
training_data.append({"class":"29:PreviousVideo", "sentence":"execute to recent video"})


training_data.append({"class":"30:Audio", "sentence":"change audio"})
training_data.append({"class":"30:Audio", "sentence":"togle audio"})

training_data.append({"class":"31:Mute", "sentence":"Mute"})
training_data.append({"class":"31:Mute", "sentence":"stop volume"})
training_data.append({"class":"31:Mute", "sentence":"volume off"})
training_data.append({"class":"31:Mute", "sentence":"speaker off"})
training_data.append({"class":"31:Mute", "sentence":"volume of"})
training_data.append({"class":"31:Mute", "sentence":"speaker of"})
training_data.append({"class":"31:Mute", "sentence":"speaker stop"})
training_data.append({"class":"31:Mute", "sentence":"voice stop"})
training_data.append({"class":"31:Mute", "sentence":"shut up"})

training_data.append({"class":"32:UnMute", "sentence":"unmute"})
training_data.append({"class":"32:UnMute", "sentence":"volume on"})
training_data.append({"class":"32:UnMute", "sentence":"turn on volume"})
training_data.append({"class":"32:UnMute", "sentence":"turn on voice"})
training_data.append({"class":"32:UnMute", "sentence":"turn on speaker"})
training_data.append({"class":"32:UnMute", "sentence":"volume start"})
training_data.append({"class":"32:UnMute", "sentence":"start volume"})
training_data.append({"class":"32:UnMute", "sentence":"on volume"})
training_data.append({"class":"32:UnMute", "sentence":"on voice"})
training_data.append({"class":"32:UnMute", "sentence":"start voice"})
training_data.append({"class":"32:UnMute", "sentence":"on speaker"})
training_data.append({"class":"32:UnMute", "sentence":"start speaker"})

training_data.append({"class":"41:EdutreeVideo", "sentence":"switch to video"})
training_data.append({"class":"41:EdutreeVideo", "sentence":"edutree video"})
training_data.append({"class":"41:EdutreeVideo", "sentence":"education video"})
training_data.append({"class":"41:EdutreeVideo", "sentence":"switch to edu tree video"})
training_data.append({"class":"41:EdutreeVideo", "sentence":"switch to edutree video"})
training_data.append({"class":"41:EdutreeVideo", "sentence":"pip on"})
training_data.append({"class":"41:EdutreeVideo", "sentence":"pip video"})
training_data.append({"class":"41:EdutreeVideo", "sentence":"play learning list video"})

training_data.append({"class":"52:Back", "sentence":"back"})
training_data.append({"class":"52:Back", "sentence":"escape"})
training_data.append({"class":"52:Back", "sentence":"go back"})

training_data.append({"class":"53:Forward URL", "sentence":"forward url"})
training_data.append({"class":"53:Forward URL", "sentence":"next url"})
training_data.append({"class":"53:Forward URL", "sentence":"forward link"})
training_data.append({"class":"53:Forward URL", "sentence":"next link"})

training_data.append({"class":"54:Backward URL", "sentence":"back url"})
training_data.append({"class":"54:Backward URL", "sentence":"backward"})
training_data.append({"class":"54:Backward URL", "sentence":"backward url"})
training_data.append({"class":"54:Backward URL", "sentence":"last url"})
training_data.append({"class":"54:Backward URL", "sentence":"previous url"})
training_data.append({"class":"54:Backward URL", "sentence":"back link"})
training_data.append({"class":"54:Backward URL", "sentence":"backward link"})
training_data.append({"class":"54:Backward URL", "sentence":"last link"})
training_data.append({"class":"54:Backward URL", "sentence":"previous link"})

training_data.append({"class":"55:Refresh URL", "sentence":"refresh url"})
training_data.append({"class":"55:Refresh URL", "sentence":"refresh url"})
training_data.append({"class":"55:Refresh URL", "sentence":"refresh link"})
training_data.append({"class":"55:Refresh URL", "sentence":"refresh link"})

training_data.append({"class":"56:Search URL", "sentence":"search url"})
training_data.append({"class":"56:Search URL", "sentence":"search"})
training_data.append({"class":"56:Search URL", "sentence":"enter url"})
training_data.append({"class":"56:Search URL", "sentence":"find url"})
training_data.append({"class":"56:Search URL", "sentence":"get url"})
training_data.append({"class":"56:Search URL", "sentence":"insert url"})
training_data.append({"class":"56:Search URL", "sentence":"add url"})
training_data.append({"class":"56:Search URL", "sentence":"input url"})
training_data.append({"class":"56:Search URL", "sentence":"search link"})
training_data.append({"class":"56:Search URL", "sentence":"enter link"})
training_data.append({"class":"56:Search URL", "sentence":"find link"})
training_data.append({"class":"56:Search URL", "sentence":"get link"})
training_data.append({"class":"56:Search URL", "sentence":"insert link"})
training_data.append({"class":"56:Search URL", "sentence":"add link"})
training_data.append({"class":"56:Search URL", "sentence":"input link"})

training_data.append({"class":"57:Globe ON", "sentence":"globe on"})
training_data.append({"class":"57:Globe ON", "sentence":"start globe"})
training_data.append({"class":"57:Globe ON", "sentence":"enlight globe"})
training_data.append({"class":"57:Globe ON", "sentence":"flash globe"})
training_data.append({"class":"57:Globe ON", "sentence":"light on"})
training_data.append({"class":"57:Globe ON", "sentence":"start light"})
training_data.append({"class":"57:Globe ON", "sentence":"enlight light"})
training_data.append({"class":"57:Globe ON", "sentence":"flash light"})
training_data.append({"class":"57:Globe ON", "sentence":"lamp on"})
training_data.append({"class":"57:Globe ON", "sentence":"start lamp"})
training_data.append({"class":"57:Globe ON", "sentence":"enlight lamp"})
training_data.append({"class":"57:Globe ON", "sentence":"flash lamp"})
training_data.append({"class":"57:Globe ON", "sentence":"bulb on"})
training_data.append({"class":"57:Globe ON", "sentence":"start bulb"})
training_data.append({"class":"57:Globe ON", "sentence":"enlight bulb"})
training_data.append({"class":"57:Globe ON", "sentence":"flash bulb"})
training_data.append({"class":"57:Globe ON", "sentence":"turn on light"})


training_data.append({"class":"58:Globe OFF", "sentence":"globe off"})
training_data.append({"class":"58:Globe OFF", "sentence":"turn off globe"})
training_data.append({"class":"58:Globe OFF", "sentence":"lamp off"})
training_data.append({"class":"58:Globe OFF", "sentence":"bulb off"})
training_data.append({"class":"58:Globe OFF", "sentence":"light off"})
training_data.append({"class":"58:Globe OFF", "sentence":"globe of"})
training_data.append({"class":"58:Globe OFF", "sentence":"turn of globe"})
training_data.append({"class":"58:Globe OFF", "sentence":"lamp of"})
training_data.append({"class":"58:Globe OFF", "sentence":"bulb of"})
training_data.append({"class":"58:Globe OFF", "sentence":"light of"})

training_data.append({"class":"59:Enable wifi", "sentence":"wifi enable"})
training_data.append({"class":"59:Enable wifi", "sentence":"wifi on"})
training_data.append({"class":"59:Enable wifi", "sentence":"turn on wifi"})
training_data.append({"class":"59:Enable wifi", "sentence":"turn on wi fi"})
training_data.append({"class":"59:Enable wifi", "sentence":"turn on wi-fi"})
training_data.append({"class":"59:Enable wifi", "sentence":"wifi connect"})
training_data.append({"class":"59:Enable wifi", "sentence":"wifi start"})
training_data.append({"class":"59:Enable wifi", "sentence":"wi-fi enable"})
training_data.append({"class":"59:Enable wifi", "sentence":"wi-fi on"})
training_data.append({"class":"59:Enable wifi", "sentence":"wi-fi connect"})
training_data.append({"class":"59:Enable wifi", "sentence":"wi-fi start"})
training_data.append({"class":"59:Enable wifi", "sentence":"wi fi enable"})
training_data.append({"class":"59:Enable wifi", "sentence":"wi fi on"})
training_data.append({"class":"59:Enable wifi", "sentence":"wi fi connect"})
training_data.append({"class":"59:Enable wifi", "sentence":"wi fi start"})

training_data.append({"class":"60:Disable wifi", "sentence":"wifi disable"})
training_data.append({"class":"60:Disable wifi", "sentence":"wifi off"})
training_data.append({"class":"60:Disable wifi", "sentence":"turn off wifi"})
training_data.append({"class":"60:Disable wifi", "sentence":"turn off wi-fi"})
training_data.append({"class":"60:Disable wifi", "sentence":"turn off wi fi"})
training_data.append({"class":"60:Disable wifi", "sentence":"wifi disconnect"})
training_data.append({"class":"60:Disable wifi", "sentence":"wifi stop"})
training_data.append({"class":"60:Disable wifi", "sentence":"wi fi disable"})
training_data.append({"class":"60:Disable wifi", "sentence":"wi fi off"})
training_data.append({"class":"60:Disable wifi", "sentence":"wi fi disconnect"})
training_data.append({"class":"60:Disable wifi", "sentence":"wi fi stop"})
training_data.append({"class":"60:Disable wifi", "sentence":"wifi disable"})
training_data.append({"class":"60:Disable wifi", "sentence":"wifi off"})
training_data.append({"class":"60:Disable wifi", "sentence":"wifi disconnect"})
training_data.append({"class":"60:Disable wifi", "sentence":"wifi stop"})

training_data.append({"class":"61:Enable hotspot", "sentence":"hotspot on"})
training_data.append({"class":"61:Enable hotspot", "sentence":"turn on hotspot"})
training_data.append({"class":"61:Enable hotspot", "sentence":"turn on the hotspot"})
training_data.append({"class":"61:Enable hotspot", "sentence":"hotspot connect"})
training_data.append({"class":"61:Enable hotspot", "sentence":"hotspot start"})
training_data.append({"class":"61:Enable hotspot", "sentence":"hotspot enable"})

training_data.append({"class":"62:Disable hotspot", "sentence":"hotspot off"})
training_data.append({"class":"62:Disable hotspot", "sentence":"turn off hotspot"})
training_data.append({"class":"62:Disable hotspot", "sentence":"turn off the hotspot"})
training_data.append({"class":"62:Disable hotspot", "sentence":"hotspot disconnect"})
training_data.append({"class":"62:Disable hotspot", "sentence":"hotspot stop"})
training_data.append({"class":"62:Disable hotspot", "sentence":"hotspot disable"})

training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"join to"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"join to wifi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"join to wi-fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"join to wi fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair to"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair to the wi fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair to the wi-fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair to the wifi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair to wi fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair to wifi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair to wi-fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair wi fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair wi-fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"pair wifi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"connect to"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"connect to wifi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"connect to wi fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"connect to wi-fi"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"connect to ssid"})
training_data.append({"class":"68:Connect to Wi-Fi", "sentence":"join to ssid"})

training_data.append({"class":"69:Switch User", "sentence":"switch user"})
training_data.append({"class":"69:Switch User", "sentence":"switch the user"})
training_data.append({"class":"69:Switch User", "sentence":"switch to user"})
training_data.append({"class":"69:Switch User", "sentence":"switch to the user"})
training_data.append({"class":"69:Switch User", "sentence":"change user"})
training_data.append({"class":"69:Switch User", "sentence":"change the user"})
training_data.append({"class":"69:Switch User", "sentence":"change to user"})
training_data.append({"class":"69:Switch User", "sentence":"change to the user"})
training_data.append({"class":"69:Switch User", "sentence":"change profile"})
training_data.append({"class":"69:Switch User", "sentence":"change to profile"})
training_data.append({"class":"69:Switch User", "sentence":"change to the profile"})
training_data.append({"class":"69:Switch User", "sentence":"switch profile"})
training_data.append({"class":"69:Switch User", "sentence":"switch to profile"})
training_data.append({"class":"69:Switch User", "sentence":"switch to the profile"})
training_data.append({"class":"69:Switch User", "sentence":"switch session"})
training_data.append({"class":"69:Switch User", "sentence":"switch to session"})
training_data.append({"class":"69:Switch User", "sentence":"switch to the session"})
training_data.append({"class":"69:Switch User", "sentence":"change session"})
training_data.append({"class":"69:Switch User", "sentence":"change to session"})
training_data.append({"class":"69:Switch User", "sentence":"change to the session"})
training_data.append({"class":"69:Switch User", "sentence":"go to the user"})
training_data.append({"class":"69:Switch User", "sentence":"go to user"})
training_data.append({"class":"69:Switch User", "sentence":"go to profile"})
training_data.append({"class":"69:Switch User", "sentence":"go to the profile"})

training_data.append({"class":"70:LogOut", "sentence":"logout"})
training_data.append({"class":"70:LogOut", "sentence":"log out"})
training_data.append({"class":"70:LogOut", "sentence":"log off"})
training_data.append({"class":"70:LogOut", "sentence":"log of"})
training_data.append({"class":"70:LogOut", "sentence":"logof"})
training_data.append({"class":"70:LogOut", "sentence":"logoff"})

training_data.append({"class":"71:Restart", "sentence":"restart"})
training_data.append({"class":"71:Restart", "sentence":"start restart"})
training_data.append({"class":"71:Restart", "sentence":"start restart process"})
training_data.append({"class":"71:Restart", "sentence":"restart edu tree"})
training_data.append({"class":"71:Restart", "sentence":"restart edutree"})
training_data.append({"class":"71:Restart", "sentence":"restart device"})
training_data.append({"class":"71:Restart", "sentence":"restart my device"})
training_data.append({"class":"71:Restart", "sentence":"reboot"})
training_data.append({"class":"71:Restart", "sentence":"start reboot"})
training_data.append({"class":"71:Restart", "sentence":"start reboot process"})
training_data.append({"class":"71:Restart", "sentence":"reboot edu tree"})
training_data.append({"class":"71:Restart", "sentence":"reboot edutree"})
training_data.append({"class":"71:Restart", "sentence":"reboot device"})
training_data.append({"class":"71:Restart", "sentence":"reboot my device"})

training_data.append({"class":"72:ShutDown", "sentence":"shutdown"})
training_data.append({"class":"72:ShutDown", "sentence":"start shut down"})
training_data.append({"class":"72:ShutDown", "sentence":"bye"})
training_data.append({"class":"72:ShutDown", "sentence":"bye bye"})
training_data.append({"class":"72:ShutDown", "sentence":"bye-bye"})
training_data.append({"class":"72:ShutDown", "sentence":"byebye"})
training_data.append({"class":"72:ShutDown", "sentence":"goodbye"})
training_data.append({"class":"72:ShutDown", "sentence":"good bye"})
training_data.append({"class":"72:ShutDown", "sentence":"see you later"})
training_data.append({"class":"72:ShutDown", "sentence":"see you soon"})
training_data.append({"class":"72:ShutDown", "sentence":"shutoff"})
training_data.append({"class":"72:ShutDown", "sentence":"shutof"})
training_data.append({"class":"72:ShutDown", "sentence":"shut of"})
training_data.append({"class":"72:ShutDown", "sentence":"shut off"})

training_data.append({"class":"73:Home APP", "sentence":"move to apps"})
training_data.append({"class":"73:Home APP", "sentence":"move to app"})
training_data.append({"class":"73:Home APP", "sentence":"move to application page"})
training_data.append({"class":"73:Home APP", "sentence":"move to main page"})
training_data.append({"class":"73:Home APP", "sentence":"move to main screen"})
training_data.append({"class":"73:Home APP", "sentence":"move to home screen"})
training_data.append({"class":"73:Home APP", "sentence":"move to home page"})
training_data.append({"class":"73:Home APP", "sentence":"go to apps"})
training_data.append({"class":"73:Home APP", "sentence":"go to app"})
training_data.append({"class":"73:Home APP", "sentence":"go to application page"})
training_data.append({"class":"73:Home APP", "sentence":"go to main page"})
training_data.append({"class":"73:Home APP", "sentence":"go to main screen"})
training_data.append({"class":"73:Home APP", "sentence":"go to home screen"})
training_data.append({"class":"73:Home APP", "sentence":"go to home page"})
training_data.append({"class":"73:Home APP", "sentence":"switch to apps"})
training_data.append({"class":"73:Home APP", "sentence":"switch to app"})
training_data.append({"class":"73:Home APP", "sentence":"switch to application page"})
training_data.append({"class":"73:Home APP", "sentence":"switch to main page"})
training_data.append({"class":"73:Home APP", "sentence":"switch to main screen"})
training_data.append({"class":"73:Home APP", "sentence":"switch to home screen"})
training_data.append({"class":"73:Home APP", "sentence":"switch to home page"})
training_data.append({"class":"73:Home APP", "sentence":"jump to apps"})
training_data.append({"class":"73:Home APP", "sentence":"jump to app"})
training_data.append({"class":"73:Home APP", "sentence":"jump to application page"})
training_data.append({"class":"73:Home APP", "sentence":"jump to main page"})
training_data.append({"class":"73:Home APP", "sentence":"jump to main screen"})
training_data.append({"class":"73:Home APP", "sentence":"jump to home screen"})
training_data.append({"class":"73:Home APP", "sentence":"jump to home page"})
training_data.append({"class":"73:Home APP", "sentence":"start apps"})
training_data.append({"class":"73:Home APP", "sentence":"start app"})
training_data.append({"class":"73:Home APP", "sentence":"start application page"})
training_data.append({"class":"73:Home APP", "sentence":"start main page"})
training_data.append({"class":"73:Home APP", "sentence":"start main screen"})
training_data.append({"class":"73:Home APP", "sentence":"start home screen"})
training_data.append({"class":"73:Home APP", "sentence":"start home page"})
training_data.append({"class":"73:Home APP", "sentence":"open apps"})
training_data.append({"class":"73:Home APP", "sentence":"open app"})
training_data.append({"class":"73:Home APP", "sentence":"open application page"})
training_data.append({"class":"73:Home APP", "sentence":"open main page"})
training_data.append({"class":"73:Home APP", "sentence":"open main screen"})
training_data.append({"class":"73:Home APP", "sentence":"open home screen"})
training_data.append({"class":"73:Home APP", "sentence":"open home page"})
training_data.append({"class":"73:Home APP", "sentence":"begin apps"})
training_data.append({"class":"73:Home APP", "sentence":"begin app"})
training_data.append({"class":"73:Home APP", "sentence":"begin application page"})
training_data.append({"class":"73:Home APP", "sentence":"begin main page"})
training_data.append({"class":"73:Home APP", "sentence":"begin main screen"})
training_data.append({"class":"73:Home APP", "sentence":"begin home screen"})
training_data.append({"class":"73:Home APP", "sentence":"begin home page"})
training_data.append({"class":"73:Home APP", "sentence":"execute apps"})
training_data.append({"class":"73:Home APP", "sentence":"execute app"})
training_data.append({"class":"73:Home APP", "sentence":"execute application page"})
training_data.append({"class":"73:Home APP", "sentence":"execute main page"})
training_data.append({"class":"73:Home APP", "sentence":"execute main screen"})
training_data.append({"class":"73:Home APP", "sentence":"execute home screen"})
training_data.append({"class":"73:Home APP", "sentence":"execute home page"})
training_data.append({"class":"73:Home APP", "sentence":"take me back to home page"})
training_data.append({"class":"73:Home APP", "sentence":"take me to home page"})
training_data.append({"class":"73:Home APP", "sentence":"get back to home page"})
training_data.append({"class":"73:Home APP", "sentence":"go to main menu"})
training_data.append({"class":"73:Home APP", "sentence":"open main menu"})
training_data.append({"class":"73:Home APP", "sentence":"switch to main menu"})
training_data.append({"class":"73:Home APP", "sentence":"go to menu"})
training_data.append({"class":"73:Home APP", "sentence":"switch to menu"})
training_data.append({"class":"73:Home APP", "sentence":"open menu"})

training_data.append({"class":"74:Settings", "sentence":"settings"})
training_data.append({"class":"74:Settings", "sentence":"setting"})
training_data.append({"class":"74:Settings", "sentence":"settings page"})
training_data.append({"class":"74:Settings", "sentence":"setting page"})
training_data.append({"class":"74:Settings", "sentence":"open settings"})
training_data.append({"class":"74:Settings", "sentence":"go to settings"})
training_data.append({"class":"74:Settings", "sentence":"switch to settings"})
training_data.append({"class":"74:Settings", "sentence":"move to settings"})
training_data.append({"class":"74:Settings", "sentence":"jump to settings"})
training_data.append({"class":"74:Settings", "sentence":"execute settings"})

training_data.append({"class":"75:Trending", "sentence":"trending page"})
training_data.append({"class":"75:Trending", "sentence":"open trending page"})
training_data.append({"class":"75:Trending", "sentence":"go to trending page"})
training_data.append({"class":"75:Trending", "sentence":"switch to trending page"})
training_data.append({"class":"75:Trending", "sentence":"move to trending page"})
training_data.append({"class":"75:Trending", "sentence":"jump to trending page"})
training_data.append({"class":"75:Trending", "sentence":"execute to trending page"})
training_data.append({"class":"75:Trending", "sentence":"trends page"})
training_data.append({"class":"75:Trending", "sentence":"trending"})

training_data.append({"class":"76:PuzzleGame", "sentence":"puzzle game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"puzzle"})
training_data.append({"class":"76:PuzzleGame", "sentence":"play puzzle"})
training_data.append({"class":"76:PuzzleGame", "sentence":"open puzzle"})
training_data.append({"class":"76:PuzzleGame", "sentence":"open puzzle game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"start puzzle game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"execute puzzle game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"go to puzzle game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"switch to puzzle game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"move to puzzle game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"jump to puzzle game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"games"})
training_data.append({"class":"76:PuzzleGame", "sentence":"play games"})
training_data.append({"class":"76:PuzzleGame", "sentence":"play game"})
training_data.append({"class":"76:PuzzleGame", "sentence":"play"})
training_data.append({"class":"76:PuzzleGame", "sentence":"play puzzle game"})

training_data.append({"class":"77:Hotstar", "sentence":"hotstar"})
training_data.append({"class":"77:Hotstar", "sentence":"open hotstar"})
training_data.append({"class":"77:Hotstar", "sentence":"start hotstar"})
training_data.append({"class":"77:Hotstar", "sentence":"go to hotstar"})
training_data.append({"class":"77:Hotstar", "sentence":"jump to hotstar"})
training_data.append({"class":"77:Hotstar", "sentence":"switch to hotstar"})
training_data.append({"class":"77:Hotstar", "sentence":"move to hotstar"})
training_data.append({"class":"77:Hotstar", "sentence":"execute hotstar"})

training_data.append({"class":"78:MX Player", "sentence":"MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"open MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"start MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"turn on MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"execute MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"go to MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"jump to MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"switch to MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"move to MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"MXPLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"open MX PLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"start MX PLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"turn on MX PLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"execute MX PLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"go to MX PLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"jump to MX PLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"switch to MX PLAYER"})
training_data.append({"class":"78:MX Player", "sentence":"move to MX PLAYER"})


training_data.append({"class":"80:RestartVideo", "sentence":"replay video"})
training_data.append({"class":"80:RestartVideo", "sentence":"start video again"})
training_data.append({"class":"80:RestartVideo", "sentence":"play video again"})


print ("%s sentences in training data" % len(training_data))

words = []
classes = []
documents = []
ignore_words = ['?']
# loop through each sentence in our training data
for pattern in training_data:
    # tokenize each word in the sentence
    w = nltk.word_tokenize(pattern['sentence'])
    # add to our words list
    words.extend(w)
    # add to documents in our corpus
    documents.append((w, pattern['class']))
    # add to our classes list
    if pattern['class'] not in classes:
        classes.append(pattern['class'])

# stem and lower each word and remove duplicates
words = [stemmer.stem(w.lower()) for w in words if w not in ignore_words]
words = list(set(words))

# remove duplicates
classes = list(set(classes))

print (len(documents), "documents")
print (len(classes), "classes", classes)
print (len(words), "unique stemmed words", words)


training = []
output = []
# create an empty array for our output
output_empty = [0] * len(classes)

# training set, bag of words for each sentence
for doc in documents:
    # initialize our bag of words
    bag = []
    # list of tokenized words for the pattern
    pattern_words = doc[0]
    # stem each word
    pattern_words = [stemmer.stem(word.lower()) for word in pattern_words]
    # create our bag of words array
    for w in words:
        bag.append(1) if w in pattern_words else bag.append(0)

    training.append(bag)
    # output is a '0' for each tag and '1' for current tag
    output_row = list(output_empty)
    output_row[classes.index(doc[1])] = 1
    output.append(output_row)

# sample training/output
i = 0
w = documents[i][0]
print ([stemmer.stem(word.lower()) for word in w])
print (training[i])
print (output[i])




# compute sigmoid nonlinearity
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

# convert output of sigmoid function to its derivative
def sigmoid_output_to_derivative(output):
    return output*(1-output)
 
def clean_up_sentence(sentence):
    # tokenize the pattern
    sentence_words = nltk.word_tokenize(sentence)
    # stem each word
    sentence_words = [stemmer.stem(word.lower()) for word in sentence_words]
    return sentence_words

# return bag of words array: 0 or 1 for each word in the bag that exists in the sentence
def bow(sentence, words, show_details=False):
    # tokenize the pattern
    sentence_words = clean_up_sentence(sentence)
    # bag of words
    bag = [0]*len(words)  
    for s in sentence_words:
        for i,w in enumerate(words):
            if w == s: 
                bag[i] = 1
                if show_details:
                    print ("found in bag: %s" % w)

    return(np.array(bag))

def think(sentence, show_details=False):
    x = bow(sentence.lower(), words, show_details)
    if show_details:
        print ("sentence:", sentence, "\n bow:", x)
    # input layer is our bag of words
    l0 = x
    # matrix multiplication of input and hidden layer
    l1 = sigmoid(np.dot(l0, synapse_0))
    # output layer
    l2 = sigmoid(np.dot(l1, synapse_1))
    return l2

def train(X, y, hidden_neurons=2, alpha=1, epochs=50000, dropout=False, dropout_percent=0.5):

    print ("Training with %s neurons, alpha:%s, dropout:%s %s" % (hidden_neurons, str(alpha), dropout, dropout_percent if dropout else '') )
    print ("Input matrix: %sx%s    Output matrix: %sx%s" % (len(X),len(X[0]),1, len(classes)) )
    np.random.seed(1)

    last_mean_error = 1
    # randomly initialize our weights with mean 0
    synapse_0 = 2*np.random.random((len(X[0]), hidden_neurons)) - 1
    synapse_1 = 2*np.random.random((hidden_neurons, len(classes))) - 1

    prev_synapse_0_weight_update = np.zeros_like(synapse_0)
    prev_synapse_1_weight_update = np.zeros_like(synapse_1)

    synapse_0_direction_count = np.zeros_like(synapse_0)
    synapse_1_direction_count = np.zeros_like(synapse_1)
        
    for j in iter(range(epochs+1)):

        # Feed forward through layers 0, 1, and 2
        layer_0 = X
        layer_1 = sigmoid(np.dot(layer_0, synapse_0))
                
        if(dropout):
            layer_1 *= np.random.binomial([np.ones((len(X),hidden_neurons))],1-dropout_percent)[0] * (1.0/(1-dropout_percent))

        layer_2 = sigmoid(np.dot(layer_1, synapse_1))

        # how much did we miss the target value?
        layer_2_error = y - layer_2

        # if (j% 10000) == 0 and j > 5000:
            # if this 10k iteration's error is greater than the last iteration, break out
        if np.mean(np.abs(layer_2_error)) < last_mean_error:
            print ("delta after "+str(j)+" iterations:" + str(np.mean(np.abs(layer_2_error))) )
            last_mean_error = np.mean(np.abs(layer_2_error))
            
                
        # in what direction is the target value?
        # were we really sure? if so, don't change too much.
        layer_2_delta = layer_2_error * sigmoid_output_to_derivative(layer_2)

        # how much did each l1 value contribute to the l2 error (according to the weights)?
        layer_1_error = layer_2_delta.dot(synapse_1.T)

        # in what direction is the target l1?
        # were we really sure? if so, don't change too much.
        layer_1_delta = layer_1_error * sigmoid_output_to_derivative(layer_1)
        
        synapse_1_weight_update = (layer_1.T.dot(layer_2_delta))
        synapse_0_weight_update = (layer_0.T.dot(layer_1_delta))
        
        if(j > 0):
            synapse_0_direction_count += np.abs(((synapse_0_weight_update > 0)+0) - ((prev_synapse_0_weight_update > 0) + 0))
            synapse_1_direction_count += np.abs(((synapse_1_weight_update > 0)+0) - ((prev_synapse_1_weight_update > 0) + 0))        
        
        synapse_1 += alpha * synapse_1_weight_update
        synapse_0 += alpha * synapse_0_weight_update
        
        prev_synapse_0_weight_update = synapse_0_weight_update
        prev_synapse_1_weight_update = synapse_1_weight_update

    now = datetime.datetime.now()

    # persist synapses
    synapse = {'synapse0': synapse_0.tolist(), 'synapse1': synapse_1.tolist(),
               'datetime': now.strftime("%Y-%m-%d %H:%M"),
               'words': words,
               'classes': classes
              }
    synapse_file = "artificial_neural_network.json"

    with open(synapse_file, 'w') as outfile:
        json.dump(synapse, outfile, indent=4, sort_keys=True)
    print ("saved synapses to:", synapse_file)



X = np.array(training)
y = np.array(output)

start_time = time.time()

train(X, y, hidden_neurons=15, alpha=0.01, epochs=1000000, dropout=False, dropout_percent=0.1)

elapsed_time = time.time() - start_time
print ("processing time:", elapsed_time, "seconds")




ERROR_THRESHOLD = 0.1
# load our calculated synapse values
synapse_file = 'artificial_neural_network.json' 
with open(synapse_file) as data_file: 
    synapse = json.load(data_file) 
    synapse_0 = np.asarray(synapse['synapse0']) 
    synapse_1 = np.asarray(synapse['synapse1'])

def classify(sentence, show_details=False):
    results = think(sentence, show_details)

    results = [[i,r] for i,r in enumerate(results) if r>=ERROR_THRESHOLD ] 
    # print(results[0][1])
    try:
        res = results[0][1]
        a = res * 100

        if(a >= 90):
            results.sort(key=lambda x: x[1], reverse=True) 
            return_results =[[classes[r[0]],r[1]] for r in results]
            print ("%s \n classification: %s" % (sentence, return_results))
            print("=================================>",return_results[0][0])
            arg = return_results[0][0]
            if(arg == '68:Connect_to_Wi-Fi' or arg == "69:Switch_user"):
                output = sentence.split()
                print(output[-1])

        elif(a <= 90 and a >=10):
            results.sort(key=lambda x: x[1], reverse=True) 
            return_results =[[classes[r[0]],r[1]] for r in results]
            print ("%s \n classification: %s" % (sentence, return_results))
            print(return_results)
            length = len(return_results)
            print(length)

            for i in range(length):
                print("did you mean")
                print(return_results[i][0])
                print(" ")
              


    except Exception as e:
                print("========================================================>No command found")           
# def classify(sentence, show_details=False):
#     results = think(sentence, show_details)

#     results = [[i,r] for i,r in enumerate(results) if r>ERROR_THRESHOLD ] 
#     # print(results[0][1])
#     a = results[0][1] * 100
#     print(a)
#     if(a > 90):
# 	    results.sort(key=lambda x: x[1], reverse=True) 
# 	    return_results =[[classes[r[0]],r[1]] for r in results]
# 	    print ("%s \n classification: %s" % (sentence, return_results))
# 	    print(return_results[0][0])

#     # return return_results

# # classify("sudo make me a sandwich")
# classify("switch to tv")
# classify("talk to you tomorrow")
# classify("who are you?")
# classify("make me some lunch")
# classify("asjfbh")
# # print()

classify("tv")
classify("Academics")
classify("gk")
classify("revision")
classify("progress applciation")
classify("tips")
classify("test")
classify("library")
classify("edueye")
classify("update application")
classify("miracast")
classify("browser")
classify("faq")
classify("wifi")
classify("ethernet")
classify("display")
classify("date")
classify("usb")
classify("learning list")
classify("reset")
classify("update setting")
classify("about")
classify("snakes")
classify("close")
classify("stop")
classify("end")
classify("play video")
classify("pause video")
classify("stop video")
classify("next video")
classify("previous video")
classify("change audio")
classify("mute")
classify("unmute")
classify("switch to video")
classify("tv shows")
classify("back")
classify("forward url")
classify("back url")
classify("refresh url")
classify("search url")
classify("globe on")
classify("globe off")
classify("wi-fi enable")
classify("wi-fi disable")
classify("hotspot enable")
classify("hotspot disable")
classify("connect to ssid")
classify("switch user")
classify("logout")
classify("restart")
classify("shutdown")
classify("move to apps")
classify("open settings")
classify("open trending")
classify("open puzzle")
classify("open hotstar")
classify("open mxplayer")
classify("replay video")
